{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": 2,
   "id": "d4088f36",
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Requirement already satisfied: earthengine-api in c:\\users\\hasee\\anaconda3\\envs\\pythonproject\\lib\\site-packages (0.1.350)\n",
      "Requirement already satisfied: google-api-python-client>=1.12.1 in c:\\users\\hasee\\anaconda3\\envs\\pythonproject\\lib\\site-packages (from earthengine-api) (2.86.0)\n",
      "Requirement already satisfied: requests in c:\\users\\hasee\\anaconda3\\envs\\pythonproject\\lib\\site-packages (from earthengine-api) (2.28.1)\n",
      "Requirement already satisfied: httplib2<1dev,>=0.9.2 in c:\\users\\hasee\\anaconda3\\envs\\pythonproject\\lib\\site-packages (from earthengine-api) (0.22.0)\n",
      "Requirement already satisfied: google-cloud-storage in c:\\users\\hasee\\anaconda3\\envs\\pythonproject\\lib\\site-packages (from earthengine-api) (2.8.0)\n",
      "Requirement already satisfied: google-auth>=1.4.1 in c:\\users\\hasee\\anaconda3\\envs\\pythonproject\\lib\\site-packages (from earthengine-api) (2.17.3)\n",
      "Requirement already satisfied: google-auth-httplib2>=0.0.3 in c:\\users\\hasee\\anaconda3\\envs\\pythonproject\\lib\\site-packages (from earthengine-api) (0.1.0)\n",
      "Requirement already satisfied: google-api-core!=2.0.*,!=2.1.*,!=2.2.*,!=2.3.0,<3.0.0dev,>=1.31.5 in c:\\users\\hasee\\anaconda3\\envs\\pythonproject\\lib\\site-packages (from google-api-python-client>=1.12.1->earthengine-api) (2.11.0)\n",
      "Requirement already satisfied: uritemplate<5,>=3.0.1 in c:\\users\\hasee\\anaconda3\\envs\\pythonproject\\lib\\site-packages (from google-api-python-client>=1.12.1->earthengine-api) (4.1.1)\n",
      "Requirement already satisfied: cachetools<6.0,>=2.0.0 in c:\\users\\hasee\\anaconda3\\envs\\pythonproject\\lib\\site-packages (from google-auth>=1.4.1->earthengine-api) (5.3.0)\n",
      "Requirement already satisfied: rsa<5,>=3.1.4 in c:\\users\\hasee\\anaconda3\\envs\\pythonproject\\lib\\site-packages (from google-auth>=1.4.1->earthengine-api) (4.9)\n",
      "Requirement already satisfied: six>=1.9.0 in c:\\users\\hasee\\anaconda3\\envs\\pythonproject\\lib\\site-packages (from google-auth>=1.4.1->earthengine-api) (1.16.0)\n",
      "Requirement already satisfied: pyasn1-modules>=0.2.1 in c:\\users\\hasee\\anaconda3\\envs\\pythonproject\\lib\\site-packages (from google-auth>=1.4.1->earthengine-api) (0.3.0)\n",
      "Requirement already satisfied: pyparsing!=3.0.0,!=3.0.1,!=3.0.2,!=3.0.3,<4,>=2.4.2 in c:\\users\\hasee\\anaconda3\\envs\\pythonproject\\lib\\site-packages (from httplib2<1dev,>=0.9.2->earthengine-api) (3.0.9)\n",
      "Requirement already satisfied: google-resumable-media>=2.3.2 in c:\\users\\hasee\\anaconda3\\envs\\pythonproject\\lib\\site-packages (from google-cloud-storage->earthengine-api) (2.5.0)\n",
      "Requirement already satisfied: google-cloud-core<3.0dev,>=2.3.0 in c:\\users\\hasee\\anaconda3\\envs\\pythonproject\\lib\\site-packages (from google-cloud-storage->earthengine-api) (2.3.2)\n",
      "Requirement already satisfied: idna<4,>=2.5 in c:\\users\\hasee\\anaconda3\\envs\\pythonproject\\lib\\site-packages (from requests->earthengine-api) (3.4)\n",
      "Requirement already satisfied: certifi>=2017.4.17 in c:\\users\\hasee\\anaconda3\\envs\\pythonproject\\lib\\site-packages (from requests->earthengine-api) (2022.9.24)\n",
      "Requirement already satisfied: charset-normalizer<3,>=2 in c:\\users\\hasee\\anaconda3\\envs\\pythonproject\\lib\\site-packages (from requests->earthengine-api) (2.0.4)\n",
      "Requirement already satisfied: urllib3<1.27,>=1.21.1 in c:\\users\\hasee\\anaconda3\\envs\\pythonproject\\lib\\site-packages (from requests->earthengine-api) (1.26.12)\n",
      "Requirement already satisfied: googleapis-common-protos<2.0dev,>=1.56.2 in c:\\users\\hasee\\anaconda3\\envs\\pythonproject\\lib\\site-packages (from google-api-core!=2.0.*,!=2.1.*,!=2.2.*,!=2.3.0,<3.0.0dev,>=1.31.5->google-api-python-client>=1.12.1->earthengine-api) (1.59.0)\n",
      "Requirement already satisfied: protobuf!=3.20.0,!=3.20.1,!=4.21.0,!=4.21.1,!=4.21.2,!=4.21.3,!=4.21.4,!=4.21.5,<5.0.0dev,>=3.19.5 in c:\\users\\hasee\\anaconda3\\envs\\pythonproject\\lib\\site-packages (from google-api-core!=2.0.*,!=2.1.*,!=2.2.*,!=2.3.0,<3.0.0dev,>=1.31.5->google-api-python-client>=1.12.1->earthengine-api) (4.22.3)\n",
      "Requirement already satisfied: google-crc32c<2.0dev,>=1.0 in c:\\users\\hasee\\anaconda3\\envs\\pythonproject\\lib\\site-packages (from google-resumable-media>=2.3.2->google-cloud-storage->earthengine-api) (1.5.0)\n",
      "Requirement already satisfied: pyasn1<0.6.0,>=0.4.6 in c:\\users\\hasee\\anaconda3\\envs\\pythonproject\\lib\\site-packages (from pyasn1-modules>=0.2.1->google-auth>=1.4.1->earthengine-api) (0.5.0)\n",
      "Note: you may need to restart the kernel to use updated packages.\n"
     ]
    }
   ],
   "source": [
    "pip install earthengine-api"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 3,
   "id": "ad89d4e2",
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Unexpected exception formatting exception. Falling back to standard exception\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\Hasee\\anaconda3\\envs\\pythonProject\\lib\\site-packages\\IPython\\core\\interactiveshell.py\", line 3433, in run_code\n",
      "  File \"C:\\Users\\Hasee\\AppData\\Local\\Temp\\ipykernel_14852\\2579516788.py\", line 1, in <module>\n",
      "    import ee\n",
      "ModuleNotFoundError: No module named 'ee'\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\Hasee\\anaconda3\\envs\\pythonProject\\lib\\site-packages\\pygments\\styles\\__init__.py\", line 78, in get_style_by_name\n",
      "ModuleNotFoundError: No module named 'pygments.styles.default'\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\Hasee\\anaconda3\\envs\\pythonProject\\lib\\site-packages\\IPython\\core\\interactiveshell.py\", line 2052, in showtraceback\n",
      "  File \"C:\\Users\\Hasee\\anaconda3\\envs\\pythonProject\\lib\\site-packages\\IPython\\core\\ultratb.py\", line 1112, in structured_traceback\n",
      "  File \"C:\\Users\\Hasee\\anaconda3\\envs\\pythonProject\\lib\\site-packages\\IPython\\core\\ultratb.py\", line 1006, in structured_traceback\n",
      "  File \"C:\\Users\\Hasee\\anaconda3\\envs\\pythonProject\\lib\\site-packages\\IPython\\core\\ultratb.py\", line 859, in structured_traceback\n",
      "  File \"C:\\Users\\Hasee\\anaconda3\\envs\\pythonProject\\lib\\site-packages\\IPython\\core\\ultratb.py\", line 793, in format_exception_as_a_whole\n",
      "  File \"C:\\Users\\Hasee\\anaconda3\\envs\\pythonProject\\lib\\site-packages\\IPython\\core\\ultratb.py\", line 838, in get_records\n",
      "  File \"C:\\Users\\Hasee\\anaconda3\\envs\\pythonProject\\lib\\site-packages\\pygments\\styles\\__init__.py\", line 80, in get_style_by_name\n",
      "pygments.util.ClassNotFound: Could not find style module 'default', though it should be builtin.\n"
     ]
    }
   ],
   "source": [
    "import ee\n",
    "import folium\n",
    "\n",
    "# 初始化Google Earth Engine\n",
    "ee.Initialize()\n",
    "\n",
    "# 定义时间范围\n",
    "start_date = '2010-01-01'\n",
    "end_date = '2010-12-31'\n",
    "\n",
    "# 定义地理范围（使用坐标定义一个矩形）\n",
    "geometry = ee.Geometry.Rectangle([103.843, 1.309, 104.041, 1.456])\n",
    "\n",
    "# 导入EO-1 Hyperion数据\n",
    "hyperion = ee.ImageCollection('EO1/HYPERION')\n",
    "\n",
    "# 过滤图像集合\n",
    "filtered = hyperion.filterDate(start_date, end_date).filterBounds(geometry)\n",
    "\n",
    "# 计算过滤后图像集合的中位数\n",
    "median_image = filtered.median()\n",
    "\n",
    "# 定义显示参数\n",
    "visualization_params = {\n",
    "    'bands': ['B29', 'B20', 'B11'],\n",
    "    'min': 0.0,\n",
    "    'max': 3000.0,\n",
    "    'gamma': 1.0\n",
    "}\n",
    "\n",
    "# 将地图添加到Folium\n",
    "def add_ee_layer(self, ee_image_object, vis_params, name):\n",
    "    map_id_dict = ee.Image(ee_image_object).getMapId(vis_params)\n",
    "    folium.raster_layers.TileLayer(\n",
    "        tiles=map_id_dict['tile_fetcher'].url_format,\n",
    "        attr='Map Data &copy; <a href=\"https://earthengine.google.com/\">Google Earth Engine</a>',\n",
    "        name=name,\n",
    "        overlay=True,\n",
    "        control=True\n",
    "    ).add_to(self)\n",
    "\n",
    "folium.Map.add_ee_layer = add_ee_layer\n",
    "\n",
    "# 创建地图对象并设置中心\n",
    "map_obj = folium.Map(location=[1.38, 103.94], zoom_start=11)\n",
    "\n",
    "# 将EO-1 Hyperion数据添加到地图\n",
    "map_obj.add_ee_layer(median_image, visualization_params, 'EO-1 Hyperion')\n",
    "\n",
    "# 添加图层控制器\n",
    "map_obj.add_child(folium.LayerControl())\n",
    "\n",
    "# 显示地图\n",
    "map_obj\n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 1,
   "id": "90a5773e",
   "metadata": {},
   "outputs": [
    {
     "ename": "EEException",
     "evalue": "Not signed up for Earth Engine or project is not registered. Visit https://developers.google.com/earth-engine/guides/access",
     "output_type": "error",
     "traceback": [
      "\u001b[1;31m---------------------------------------------------------------------------\u001b[0m",
      "\u001b[1;31mHttpError\u001b[0m                                 Traceback (most recent call last)",
      "File \u001b[1;32m~\\anaconda3\\lib\\site-packages\\ee\\data.py:337\u001b[0m, in \u001b[0;36m_execute_cloud_call\u001b[1;34m(call, num_retries)\u001b[0m\n\u001b[0;32m    336\u001b[0m \u001b[38;5;28;01mtry\u001b[39;00m:\n\u001b[1;32m--> 337\u001b[0m   \u001b[38;5;28;01mreturn\u001b[39;00m \u001b[43mcall\u001b[49m\u001b[38;5;241;43m.\u001b[39;49m\u001b[43mexecute\u001b[49m\u001b[43m(\u001b[49m\u001b[43mnum_retries\u001b[49m\u001b[38;5;241;43m=\u001b[39;49m\u001b[43mnum_retries\u001b[49m\u001b[43m)\u001b[49m\n\u001b[0;32m    338\u001b[0m \u001b[38;5;28;01mexcept\u001b[39;00m googleapiclient\u001b[38;5;241m.\u001b[39merrors\u001b[38;5;241m.\u001b[39mHttpError \u001b[38;5;28;01mas\u001b[39;00m e:\n",
      "File \u001b[1;32m~\\anaconda3\\lib\\site-packages\\googleapiclient\\_helpers.py:130\u001b[0m, in \u001b[0;36mpositional.<locals>.positional_decorator.<locals>.positional_wrapper\u001b[1;34m(*args, **kwargs)\u001b[0m\n\u001b[0;32m    129\u001b[0m         logger\u001b[38;5;241m.\u001b[39mwarning(message)\n\u001b[1;32m--> 130\u001b[0m \u001b[38;5;28;01mreturn\u001b[39;00m wrapped(\u001b[38;5;241m*\u001b[39margs, \u001b[38;5;241m*\u001b[39m\u001b[38;5;241m*\u001b[39mkwargs)\n",
      "File \u001b[1;32m~\\anaconda3\\lib\\site-packages\\googleapiclient\\http.py:938\u001b[0m, in \u001b[0;36mHttpRequest.execute\u001b[1;34m(self, http, num_retries)\u001b[0m\n\u001b[0;32m    937\u001b[0m \u001b[38;5;28;01mif\u001b[39;00m resp\u001b[38;5;241m.\u001b[39mstatus \u001b[38;5;241m>\u001b[39m\u001b[38;5;241m=\u001b[39m \u001b[38;5;241m300\u001b[39m:\n\u001b[1;32m--> 938\u001b[0m     \u001b[38;5;28;01mraise\u001b[39;00m HttpError(resp, content, uri\u001b[38;5;241m=\u001b[39m\u001b[38;5;28mself\u001b[39m\u001b[38;5;241m.\u001b[39muri)\n\u001b[0;32m    939\u001b[0m \u001b[38;5;28;01mreturn\u001b[39;00m \u001b[38;5;28mself\u001b[39m\u001b[38;5;241m.\u001b[39mpostproc(resp, content)\n",
      "\u001b[1;31mHttpError\u001b[0m: <HttpError 403 when requesting https://earthengine.googleapis.com/v1alpha/projects/earthengine-legacy/algorithms?prettyPrint=false&alt=json returned \"Not signed up for Earth Engine or project is not registered. Visit https://developers.google.com/earth-engine/guides/access\". Details: \"Not signed up for Earth Engine or project is not registered. Visit https://developers.google.com/earth-engine/guides/access\">",
      "\nDuring handling of the above exception, another exception occurred:\n",
      "\u001b[1;31mEEException\u001b[0m                               Traceback (most recent call last)",
      "Input \u001b[1;32mIn [1]\u001b[0m, in \u001b[0;36m<cell line: 5>\u001b[1;34m()\u001b[0m\n\u001b[0;32m      2\u001b[0m \u001b[38;5;28;01mimport\u001b[39;00m \u001b[38;5;21;01mfolium\u001b[39;00m\n\u001b[0;32m      4\u001b[0m \u001b[38;5;66;03m# 初始化Google Earth Engine\u001b[39;00m\n\u001b[1;32m----> 5\u001b[0m \u001b[43mee\u001b[49m\u001b[38;5;241;43m.\u001b[39;49m\u001b[43mInitialize\u001b[49m\u001b[43m(\u001b[49m\u001b[43m)\u001b[49m\n\u001b[0;32m      7\u001b[0m \u001b[38;5;66;03m# 定义时间范围\u001b[39;00m\n\u001b[0;32m      8\u001b[0m start_date \u001b[38;5;241m=\u001b[39m \u001b[38;5;124m'\u001b[39m\u001b[38;5;124m2010-01-01\u001b[39m\u001b[38;5;124m'\u001b[39m\n",
      "File \u001b[1;32m~\\anaconda3\\lib\\site-packages\\ee\\__init__.py:140\u001b[0m, in \u001b[0;36mInitialize\u001b[1;34m(credentials, opt_url, cloud_api_key, http_transport, project)\u001b[0m\n\u001b[0;32m    131\u001b[0m data\u001b[38;5;241m.\u001b[39minitialize(\n\u001b[0;32m    132\u001b[0m     credentials\u001b[38;5;241m=\u001b[39mcredentials,\n\u001b[0;32m    133\u001b[0m     api_base_url\u001b[38;5;241m=\u001b[39m(opt_url \u001b[38;5;241m+\u001b[39m \u001b[38;5;124m'\u001b[39m\u001b[38;5;124m/api\u001b[39m\u001b[38;5;124m'\u001b[39m \u001b[38;5;28;01mif\u001b[39;00m opt_url \u001b[38;5;28;01melse\u001b[39;00m \u001b[38;5;28;01mNone\u001b[39;00m),\n\u001b[1;32m   (...)\u001b[0m\n\u001b[0;32m    137\u001b[0m     project\u001b[38;5;241m=\u001b[39mproject,\n\u001b[0;32m    138\u001b[0m     http_transport\u001b[38;5;241m=\u001b[39mhttp_transport)\n\u001b[0;32m    139\u001b[0m \u001b[38;5;66;03m# Initialize the dynamically loaded functions on the objects that want them.\u001b[39;00m\n\u001b[1;32m--> 140\u001b[0m \u001b[43mApiFunction\u001b[49m\u001b[38;5;241;43m.\u001b[39;49m\u001b[43minitialize\u001b[49m\u001b[43m(\u001b[49m\u001b[43m)\u001b[49m\n\u001b[0;32m    141\u001b[0m Element\u001b[38;5;241m.\u001b[39minitialize()\n\u001b[0;32m    142\u001b[0m Image\u001b[38;5;241m.\u001b[39minitialize()\n",
      "File \u001b[1;32m~\\anaconda3\\lib\\site-packages\\ee\\apifunction.py:154\u001b[0m, in \u001b[0;36mApiFunction.initialize\u001b[1;34m(cls)\u001b[0m\n\u001b[0;32m    152\u001b[0m \u001b[38;5;124;03m\"\"\"Initializes the list of signatures from the Earth Engine front-end.\"\"\"\u001b[39;00m\n\u001b[0;32m    153\u001b[0m \u001b[38;5;28;01mif\u001b[39;00m \u001b[38;5;129;01mnot\u001b[39;00m \u001b[38;5;28mcls\u001b[39m\u001b[38;5;241m.\u001b[39m_api:\n\u001b[1;32m--> 154\u001b[0m   signatures \u001b[38;5;241m=\u001b[39m \u001b[43mdata\u001b[49m\u001b[38;5;241;43m.\u001b[39;49m\u001b[43mgetAlgorithms\u001b[49m\u001b[43m(\u001b[49m\u001b[43m)\u001b[49m\n\u001b[0;32m    155\u001b[0m   api \u001b[38;5;241m=\u001b[39m {}\n\u001b[0;32m    156\u001b[0m   \u001b[38;5;28;01mfor\u001b[39;00m name, sig \u001b[38;5;129;01min\u001b[39;00m signatures\u001b[38;5;241m.\u001b[39mitems():\n\u001b[0;32m    157\u001b[0m     \u001b[38;5;66;03m# Strip type parameters.\u001b[39;00m\n",
      "File \u001b[1;32m~\\anaconda3\\lib\\site-packages\\ee\\data.py:1268\u001b[0m, in \u001b[0;36mgetAlgorithms\u001b[1;34m()\u001b[0m\n\u001b[0;32m   1263\u001b[0m     \u001b[38;5;28mprint\u001b[39m(\n\u001b[0;32m   1264\u001b[0m         \u001b[38;5;124m'\u001b[39m\u001b[38;5;124m*** Earth Engine ***\u001b[39m\u001b[38;5;124m'\u001b[39m,\n\u001b[0;32m   1265\u001b[0m         response[_INIT_MESSAGE_HEADER],\n\u001b[0;32m   1266\u001b[0m         file\u001b[38;5;241m=\u001b[39msys\u001b[38;5;241m.\u001b[39mstderr)\n\u001b[0;32m   1267\u001b[0m call\u001b[38;5;241m.\u001b[39madd_response_callback(inspect)\n\u001b[1;32m-> 1268\u001b[0m \u001b[38;5;28;01mreturn\u001b[39;00m _cloud_api_utils\u001b[38;5;241m.\u001b[39mconvert_algorithms(\u001b[43m_execute_cloud_call\u001b[49m\u001b[43m(\u001b[49m\u001b[43mcall\u001b[49m\u001b[43m)\u001b[49m)\n",
      "File \u001b[1;32m~\\anaconda3\\lib\\site-packages\\ee\\data.py:339\u001b[0m, in \u001b[0;36m_execute_cloud_call\u001b[1;34m(call, num_retries)\u001b[0m\n\u001b[0;32m    337\u001b[0m   \u001b[38;5;28;01mreturn\u001b[39;00m call\u001b[38;5;241m.\u001b[39mexecute(num_retries\u001b[38;5;241m=\u001b[39mnum_retries)\n\u001b[0;32m    338\u001b[0m \u001b[38;5;28;01mexcept\u001b[39;00m googleapiclient\u001b[38;5;241m.\u001b[39merrors\u001b[38;5;241m.\u001b[39mHttpError \u001b[38;5;28;01mas\u001b[39;00m e:\n\u001b[1;32m--> 339\u001b[0m   \u001b[38;5;28;01mraise\u001b[39;00m _translate_cloud_exception(e)\n",
      "\u001b[1;31mEEException\u001b[0m: Not signed up for Earth Engine or project is not registered. Visit https://developers.google.com/earth-engine/guides/access"
     ]
    }
   ],
   "source": [
    "import ee\n",
    "import folium\n",
    "\n",
    "# 初始化Google Earth Engine\n",
    "ee.Initialize()\n",
    "\n",
    "# 定义时间范围\n",
    "start_date = '2010-01-01'\n",
    "end_date = '2010-12-31'\n",
    "\n",
    "# 定义地理范围（使用坐标定义一个矩形）\n",
    "geometry = ee.Geometry.Rectangle([103.843, 1.309, 104.041, 1.456])\n",
    "\n",
    "# 导入EO-1 Hyperion数据\n",
    "hyperion = ee.ImageCollection('EO1/HYPERION')\n",
    "\n",
    "# 过滤图像集合\n",
    "filtered = hyperion.filterDate(start_date, end_date).filterBounds(geometry)\n",
    "\n",
    "# 计算过滤后图像集合的中位数\n",
    "median_image = filtered.median()\n",
    "\n",
    "# 定义显示参数\n",
    "visualization_params = {\n",
    "    'bands': ['B29', 'B20', 'B11'],\n",
    "    'min': 0.0,\n",
    "    'max': 3000.0,\n",
    "    'gamma': 1.0\n",
    "}\n",
    "\n",
    "# 将地图添加到Folium\n",
    "def add_ee_layer(self, ee_image_object, vis_params, name):\n",
    "    map_id_dict = ee.Image(ee_image_object).getMapId(vis_params)\n",
    "    folium.raster_layers.TileLayer(\n",
    "        tiles=map_id_dict['tile_fetcher'].url_format,\n",
    "        attr='Map Data &copy; <a href=\"https://earthengine.google.com/\">Google Earth Engine</a>',\n",
    "        name=name,\n",
    "        overlay=True,\n",
    "        control=True\n",
    "    ).add_to(self)\n",
    "\n",
    "folium.Map.add_ee_layer = add_ee_layer\n",
    "\n",
    "# 创建地图对象并设置中心\n",
    "map_obj = folium.Map(location=[1.38, 103.94], zoom_start=11)\n",
    "\n",
    "# 将EO-1 Hyperion数据添加到地图\n",
    "map_obj.add_ee_layer(median_image, visualization_params, 'EO-1 Hyperion')\n",
    "\n",
    "# 添加图层控制器\n",
    "map_obj.add_child(folium.LayerControl())\n",
    "\n",
    "# 显示地图\n",
    "map_obj\n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "d8a67e1e",
   "metadata": {},
   "outputs": [],
   "source": []
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3 (ipykernel)",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.9.12"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 5
}
